2018-04-03 07:08:40.048452: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-04-03 07:08:40.048499: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-04-03 07:08:40.048504: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-04-03 07:08:40.048508: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-04-03 07:08:40.048512: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2018-04-03 07:08:42.917675: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties: 
name: Tesla P100-SXM2-16GB
major: 6 minor: 0 memoryClockRate (GHz) 1.4805
pciBusID 0000:07:00.0
Total memory: 15.89GiB
Free memory: 15.61GiB
2018-04-03 07:08:42.917728: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0 
2018-04-03 07:08:42.917735: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y 
2018-04-03 07:08:42.917745: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla P100-SXM2-16GB, pci bus id: 0000:07:00.0)
['S01']
[]
[]
Loading images  ../dataset/*.jpeg ['S01']
Number of images: 6200
Number of rows: 256
Number of cols: 256
Dataset array size:  (6200, 256, 256, 1)
(3100, 256, 256, 1)
(1550, 256, 256, 1)
(1550, 256, 256, 1)



| Training Step | Cross Entropy |  Layer  |   Epoch  |
|---------------|---------------|---------|----------|
|             0 |    54280.5430 | Layer 1 | Epoch 1  |
|          5000 |    20839.1270 | Layer 1 | Epoch 2  |
|         10000 |    19414.5410 | Layer 1 | Epoch 4  |
|         15000 |    18871.0605 | Layer 1 | Epoch 5  |
|         20000 |    18215.1426 | Layer 1 | Epoch 7  |
|         25000 |    17591.2617 | Layer 1 | Epoch 9  |
|         30000 |    17597.9727 | Layer 1 | Epoch 10  |
|         35000 |    17268.3516 | Layer 1 | Epoch 12  |
|         40000 |    17068.7070 | Layer 1 | Epoch 13  |
|         45000 |    16545.2168 | Layer 1 | Epoch 15  |
|         50000 |    16740.7148 | Layer 1 | Epoch 17  |
|         55000 |    16403.7578 | Layer 1 | Epoch 18  |
|         60000 |    16537.0234 | Layer 1 | Epoch 20  |
|         65000 |    16165.7031 | Layer 1 | Epoch 21  |
|         70000 |    16606.1953 | Layer 1 | Epoch 23  |
|         75000 |    16257.5078 | Layer 1 | Epoch 25  |
|         80000 |    16294.4277 | Layer 1 | Epoch 26  |
|         85000 |    16242.3447 | Layer 1 | Epoch 28  |
|         90000 |    16108.8555 | Layer 1 | Epoch 30  |
|         95000 |    16260.7188 | Layer 1 | Epoch 31  |
|        100000 |    16015.5781 | Layer 1 | Epoch 33  |
|        105000 |    15885.8389 | Layer 1 | Epoch 34  |
|        110000 |    16052.4756 | Layer 1 | Epoch 36  |
|        115000 |    15557.8203 | Layer 1 | Epoch 38  |
|        120000 |    15859.1660 | Layer 1 | Epoch 39  |
|        125000 |    16033.4766 | Layer 1 | Epoch 41  |
|        130000 |    16427.6680 | Layer 1 | Epoch 42  |
|        135000 |    16102.1338 | Layer 1 | Epoch 44  |
|        140000 |    15993.8369 | Layer 1 | Epoch 46  |
|        145000 |    15953.5449 | Layer 1 | Epoch 47  |
|        150000 |    15955.3574 | Layer 1 | Epoch 49  |



| Training Step | Cross Entropy |  Layer  |   Epoch  |
|---------------|---------------|---------|----------|
|             0 |     7525.3755 | Layer 2 | Epoch 1  |
|          5000 |     4268.4941 | Layer 2 | Epoch 2  |
|         10000 |     4072.9375 | Layer 2 | Epoch 4  |
|         15000 |     3907.6665 | Layer 2 | Epoch 5  |
|         20000 |     3913.6201 | Layer 2 | Epoch 7  |
|         25000 |     3776.2507 | Layer 2 | Epoch 9  |
|         30000 |     3703.0212 | Layer 2 | Epoch 10  |
|         35000 |     3708.2153 | Layer 2 | Epoch 12  |
|         40000 |     3800.5881 | Layer 2 | Epoch 13  |
|         45000 |     3717.8132 | Layer 2 | Epoch 15  |
|         50000 |     3748.8357 | Layer 2 | Epoch 17  |
|         55000 |     3767.1753 | Layer 2 | Epoch 18  |
|         60000 |     3717.0911 | Layer 2 | Epoch 20  |
|         65000 |     3607.7986 | Layer 2 | Epoch 21  |
|         70000 |     3658.7375 | Layer 2 | Epoch 23  |
|         75000 |     3671.6064 | Layer 2 | Epoch 25  |
Traceback (most recent call last):
  File "autoencoder.py", line 490, in <module>
    ae = main_unsupervised()
  File "autoencoder.py", line 343, in main_unsupervised
    summary_str = sess.run(summary_op, feed_dict=feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Nan in summary histogram for: pretrain_2/autoencoder_variables/weights2
	 [[Node: pretrain_2/autoencoder_variables/weights2 = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](pretrain_2/autoencoder_variables/weights2/tag, autoencoder_variables/weights2/read/_191)]]

Caused by op u'pretrain_2/autoencoder_variables/weights2', defined at:
  File "autoencoder.py", line 490, in <module>
    ae = main_unsupervised()
  File "autoencoder.py", line 324, in main_unsupervised
    for v in summary_vars]
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/summary/summary.py", line 192, in histogram
    tag=tag, values=values, name=scope)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_logging_ops.py", line 129, in _histogram_summary
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Nan in summary histogram for: pretrain_2/autoencoder_variables/weights2
	 [[Node: pretrain_2/autoencoder_variables/weights2 = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](pretrain_2/autoencoder_variables/weights2/tag, autoencoder_variables/weights2/read/_191)]]

